# Generated by Django 4.0.1 on 2022-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='fotos/')),
                ('musicSrc', models.FileField(upload_to='musicas/')),
                ('year', models.IntegerField()),
                ('album', models.CharField(max_length=100)),
            ],
        ),
    ]
